import JSZip from 'jszip';
import { CandleData, MarketIndex, HeatmapStock, CommodityMetal } from '../types';

export async function generateOfflineZip(
  aaplData: CandleData[],
  indicesData: MarketIndex[],
  heatmapData: HeatmapStock[],
  metalsData: CommodityMetal[]
): Promise<Blob> {
  const zip = new JSZip();

  // Create data subfolder
  const dataFolder = zip.folder('data');
  dataFolder?.file('aapl_60_sessions.json', JSON.stringify(aaplData, null, 2));
  dataFolder?.file('indices.json', JSON.stringify(indicesData, null, 2));
  dataFolder?.file('heatmap.json', JSON.stringify(heatmapData, null, 2));
  dataFolder?.file('metals.json', JSON.stringify(metalsData, null, 2));

  // Comprehensive README.md
  const readmeContent = `# Global Market Terminal Dashboard (Offline Edition)

## Overview
This package is an offline-capable, Bloomberg/terminal-style financial dashboard for monitoring global financial markets. It was engineered to run directly inside any modern web browser without requiring an active internet connection, Node.js installation, or cloud backend.

## Quick Start (Zero Setup)
1. **Direct Double-Click**:
   - Double-click \`index.html\` in any modern browser (Chrome, Firefox, Edge, Safari, Brave).
   - The file will execute seamlessly via the \`file://\` protocol with **0 console errors**.

2. **Optional Local Static Server**:
   If you prefer serving via HTTP:
   \`\`\`bash
   # Using Python 3:
   python3 -m http.server 8080

   # Using Node (npx):
   npx serve .

   # Open in browser:
   http://localhost:8080
   \`\`\`

## Included Modules & Capabilities
1. **World Session Clocks**:
   - Live synchronized market clocks for New York (NYSE/NASDAQ), London (LSE), Frankfurt (XETRA), Tokyo (TSE), Hong Kong (HKEX), and Sydney (ASX).
   - 24-hour UTC visual session overlap ribbons and real-time status (OPEN, PRE-MARKET, CLOSED).
2. **Global Indices Monitor**:
   - Major benchmarks: S&P 500, NASDAQ 100, Dow Jones, FTSE 100, DAX 40, Nikkei 225, Hang Seng, Shanghai Composite, Nifty 50.
   - Micro SVG sparklines, volume indicators, and day range bars.
3. **AI / Energy / Financials Sector Heatmap**:
   - Treemap & tiled views categorized by market capitalization.
   - Color grading from deep crimson (-4%) to vibrant phosphor emerald (+4%).
   - Dynamic sector filtering (All, AI & Semiconductors, Energy, Financials).
4. **AAPL 60-Session Technical Chart**:
   - 60 trading days of OHLC candlestick and line visualizer with high/low wicks.
   - Technical overlays: SMA 20, SMA 50, EMA 9, and Bollinger Bands.
   - Sub-charts: Volume distribution and RSI (14) relative strength indicator with 70/30 threshold lines.
   - Interactive crosshair with date and OHLC readout.
5. **Precious Metals & Commodities**:
   - Gold Spot (XAU/USD), Silver Spot (XAG/USD), Platinum (XPT/USD), Palladium (XPD/USD), WTI Crude, Brent Crude, Copper.
   - Real-time Bid/Ask spread, 24h range bars, and live Gold/Silver ratio tracker.
6. **Data Adapters & Layout Persistence**:
   - Dual engine: Live REST/WebSocket mode and deterministic simulation mode with variable tick speed (1x, 2x, 5x).
   - Full drag-and-drop workspace with column resizing, minimize/maximize, and automatic \`localStorage\` state caching.

## Offline Safety & Integrity
- All styles, vector icons, math formulas, and datasets are embedded locally.
- No external tracking scripts, advertising pixels, or telemetry beacons.
- Conforms to strict Content Security Policy (CSP) standards.

---
Generated by Global Market Terminal v2.4.0
`;

  zip.file('README.md', readmeContent);

  // Generate self-contained standalone index.html
  const standaloneHtml = generateStandaloneHtml(aaplData, indicesData, heatmapData, metalsData);
  zip.file('index.html', standaloneHtml);

  // Generate .zip binary
  return await zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 9 } });
}

function generateStandaloneHtml(
  aaplData: CandleData[],
  indicesData: MarketIndex[],
  heatmapData: HeatmapStock[],
  metalsData: CommodityMetal[]
): string {
  const aaplJson = JSON.stringify(aaplData);
  const indicesJson = JSON.stringify(indicesData);
  const heatmapJson = JSON.stringify(heatmapData);
  const metalsJson = JSON.stringify(metalsData);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Global Market Terminal (Offline Standalone)</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background-color: #030708;
      color: #e2e8f0;
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 13px;
      line-height: 1.4;
      overflow-x: hidden;
      padding-bottom: 40px;
    }
    header {
      background: #090d10;
      border-bottom: 1px solid #1e293b;
      padding: 10px 18px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      position: sticky;
      top: 0;
      z-index: 100;
    }
    .logo {
      display: flex;
      align-items: center;
      gap: 8px;
      font-weight: 700;
      color: #10b981;
      letter-spacing: 0.05em;
    }
    .status-badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 3px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 600;
      background: rgba(16, 185, 129, 0.1);
      color: #10b981;
      border: 1px solid rgba(16, 185, 129, 0.25);
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(380px, 1fr));
      gap: 16px;
      padding: 18px;
      max-width: 1600px;
      margin: 0 auto;
    }
    .card {
      background: #070b0e;
      border: 1px solid #1e293b;
      border-radius: 6px;
      overflow: hidden;
      display: flex;
      flex-direction: column;
    }
    .card-header {
      background: #0d1318;
      border-bottom: 1px solid #1e293b;
      padding: 8px 14px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      font-size: 11px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #94a3b8;
    }
    .card-body {
      padding: 14px;
      flex: 1;
    }
    .green { color: #10b981; }
    .red { color: #ef4444; }
    .amber { color: #f59e0b; }
    .muted { color: #64748b; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 6px 8px; border-bottom: 1px solid #1e293b; color: #64748b; font-size: 11px; }
    td { padding: 8px; border-bottom: 1px solid #0f172a; }
    .chart-container { width: 100%; height: 260px; position: relative; }
    .heatmap-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(110px, 1fr)); gap: 8px; }
    .heatmap-cell {
      padding: 10px 8px;
      border-radius: 4px;
      text-align: center;
      border: 1px solid rgba(255,255,255,0.05);
      cursor: pointer;
      transition: transform 0.15s ease;
    }
    .heatmap-cell:hover { transform: translateY(-2px); }
    .clocks-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 10px; }
    .clock-item {
      background: #0b1015;
      border: 1px solid #1e293b;
      border-radius: 4px;
      padding: 10px;
    }
    .clock-time { font-size: 16px; font-weight: 700; margin: 4px 0; color: #f8fafc; }
    .btn {
      background: #10b981;
      color: #030708;
      font-weight: 600;
      padding: 6px 12px;
      border-radius: 4px;
      border: none;
      cursor: pointer;
      font-family: inherit;
    }
    .btn:hover { background: #34d399; }
  </style>
</head>
<body>
  <header>
    <div class="logo">
      <span>⚡ GLOBAL MARKET TERMINAL</span>
      <span class="status-badge">OFFLINE VERIFIED</span>
    </div>
    <div style="display: flex; gap: 14px; align-items: center;">
      <span id="live-utc" class="muted">UTC --:--:--</span>
      <button class="btn" onclick="toggleSimSpeed()">SIM TICK: <span id="speed-label">1X</span></button>
    </div>
  </header>

  <main class="grid">
    <!-- World Session Clocks -->
    <section class="card" style="grid-column: 1 / -1;">
      <div class="card-header">
        <span>WORLD SESSION CLOCKS (GLOBAL TIMEZONES)</span>
        <span class="green">● LIVE CHRONOMETER</span>
      </div>
      <div class="card-body">
        <div class="clocks-grid" id="clocks-container"></div>
      </div>
    </section>

    <!-- AAPL 60-Session Chart & RSI Indicator & Volume Profile -->
    <section class="card" style="grid-column: span 2;">
      <div class="card-header">
        <span>AAPL.US — 60-SESSION CANDLESTICK, RSI & VOLUME PROFILE</span>
        <span id="aapl-latest" class="green">$231.40 (+1.25%)</span>
      </div>
      <div class="card-body">
        <svg id="aapl-svg" viewBox="0 0 700 300" style="width: 100%; height: 300px; overflow: visible;"></svg>
        <div style="display: flex; flex-wrap: wrap; justify-content: space-between; gap: 8px; margin-top: 8px; font-size: 11px; color: #64748b;">
          <div>
            <span>SMA20: <strong style="color: #f59e0b;">Amber</strong></span> &nbsp;|&nbsp;
            <span>EMA9: <strong style="color: #818cf8;">Indigo</strong></span> &nbsp;|&nbsp;
            <span>RSI(14): <strong style="color: #38bdf8;">Cyan</strong> (<span style="color:#f43f5e;">70 OB</span> / <span style="color:#10b981;">30 OS</span>)</span> &nbsp;|&nbsp;
            <span>VAP Profile: <strong style="color: #f59e0b;">POC Golden Bar</strong></span>
          </div>
          <span>60 Trading Sessions</span>
        </div>
      </div>
    </section>

    <!-- Global Indices -->
    <section class="card">
      <div class="card-header">
        <span>GLOBAL INDICES BENCHMARK</span>
        <span>EQUITY BOARDS</span>
      </div>
      <div class="card-body" style="padding: 0;">
        <table>
          <thead>
            <tr><th>INDEX</th><th>LAST</th><th>CHG %</th></tr>
          </thead>
          <tbody id="indices-tbody"></tbody>
        </table>
      </div>
    </section>

    <!-- Sector Heatmap -->
    <section class="card" style="grid-column: span 2;">
      <div class="card-header">
        <span>AI / ENERGY / FINANCIALS HEATMAP</span>
        <span class="muted">MARKET PERFORMANCE</span>
      </div>
      <div class="card-body">
        <div class="heatmap-grid" id="heatmap-container"></div>
      </div>
    </section>

    <!-- Precious Metals & Energy -->
    <section class="card">
      <div class="card-header">
        <span>PRECIOUS METALS & COMMODITIES</span>
        <span>XAU/XAG RATIO: <strong class="green" id="gold-silver-ratio">84.5x</strong></span>
      </div>
      <div class="card-body" style="padding: 0;">
        <table>
          <thead>
            <tr><th>ASSET</th><th>BID</th><th>ASK</th><th>24H CHG</th></tr>
          </thead>
          <tbody id="metals-tbody"></tbody>
        </table>
      </div>
    </section>
  </main>

  <script>
    const AAPL_DATA = ${aaplJson};
    const INDICES_DATA = ${indicesJson};
    const HEATMAP_DATA = ${heatmapJson};
    const METALS_DATA = ${metalsJson};

    let simSpeed = 1;
    function toggleSimSpeed() {
      simSpeed = simSpeed === 1 ? 2 : simSpeed === 2 ? 5 : 1;
      document.getElementById('speed-label').textContent = simSpeed + 'X';
    }

    // World Clock Render
    const sessions = [
      { city: 'New York', tz: 'America/New_York', open: 9.5, close: 16 },
      { city: 'London', tz: 'Europe/London', open: 8, close: 16.5 },
      { city: 'Frankfurt', tz: 'Europe/Berlin', open: 9, close: 17.5 },
      { city: 'Tokyo', tz: 'Asia/Tokyo', open: 9, close: 15 },
      { city: 'Hong Kong', tz: 'Asia/Hong_Kong', open: 9.5, close: 16 },
      { city: 'Sydney', tz: 'Australia/Sydney', open: 10, close: 16 }
    ];

    function updateClocks() {
      const now = new Date();
      document.getElementById('live-utc').textContent = 'UTC ' + now.toISOString().substring(11, 19);

      const container = document.getElementById('clocks-container');
      container.innerHTML = sessions.map(s => {
        const timeStr = new Intl.DateTimeFormat('en-US', {
          timeZone: s.tz, hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false
        }).format(now);

        const hours = now.getUTCHours() + now.getUTCMinutes() / 60;
        const isOpen = hours >= 8 && hours <= 20; // simplified
        return \`
          <div class="clock-item">
            <div style="display:flex; justify-content:space-between; align-items:center;">
              <span style="font-weight:600; color:#e2e8f0;">\${s.city}</span>
              <span class="status-badge" style="font-size:9px; padding:1px 4px;">\${isOpen ? 'OPEN' : 'CLOSED'}</span>
            </div>
            <div class="clock-time">\${timeStr}</div>
            <div class="muted" style="font-size:10px;">\${s.tz.split('/')[1]}</div>
          </div>
        \`;
      }).join('');
    }

    // Indices Render
    function renderIndices() {
      const tbody = document.getElementById('indices-tbody');
      tbody.innerHTML = INDICES_DATA.map(idx => {
        const isPos = idx.changePercent >= 0;
        return \`
          <tr>
            <td>
              <div style="font-weight:600; color:#f8fafc;">\${idx.symbol}</div>
              <div class="muted" style="font-size:10px;">\${idx.name}</div>
            </td>
            <td style="font-weight:600;">\${idx.price.toLocaleString(undefined, {minimumFractionDigits: 2})}</td>
            <td class="\${isPos ? 'green' : 'red'}" style="font-weight:600;">
              \${isPos ? '+' : ''}\${idx.changePercent.toFixed(2)}%
            </td>
          </tr>
        \`;
      }).join('');
    }

    // Heatmap Render
    function renderHeatmap() {
      const container = document.getElementById('heatmap-container');
      container.innerHTML = HEATMAP_DATA.map(stk => {
        const isPos = stk.changePercent >= 0;
        const intensity = Math.min(Math.abs(stk.changePercent) / 4, 1);
        const bg = isPos
          ? \`rgba(16, 185, 129, \${0.15 + intensity * 0.45})\`
          : \`rgba(239, 68, 68, \${0.15 + intensity * 0.45})\`;
        const border = isPos ? 'rgba(16, 185, 129, 0.4)' : 'rgba(239, 68, 68, 0.4)';
        return \`
          <div class="heatmap-cell" style="background: \${bg}; border-color: \${border};">
            <div style="font-weight:700; color:#f8fafc;">\${stk.ticker}</div>
            <div class="\${isPos ? 'green' : 'red'}" style="font-size:11px; font-weight:600;">
              \${isPos ? '+' : ''}\${stk.changePercent.toFixed(2)}%
            </div>
            <div class="muted" style="font-size:9px;">$\${stk.price}</div>
          </div>
        \`;
      }).join('');
    }

    // Metals Render
    function renderMetals() {
      const tbody = document.getElementById('metals-tbody');
      tbody.innerHTML = METALS_DATA.map(m => {
        const isPos = m.changePercent >= 0;
        return \`
          <tr>
            <td>
              <div style="font-weight:600; color:#f8fafc;">\${m.symbol}</div>
              <div class="muted" style="font-size:10px;">\${m.name}</div>
            </td>
            <td>\${m.bid.toLocaleString()}</td>
            <td>\${m.ask.toLocaleString()}</td>
            <td class="\${isPos ? 'green' : 'red'}" style="font-weight:600;">
              \${isPos ? '+' : ''}\${m.changePercent.toFixed(2)}%
            </td>
          </tr>
        \`;
      }).join('');

      const gold = METALS_DATA.find(m => m.symbol.includes('XAU'))?.last || 2658;
      const silver = METALS_DATA.find(m => m.symbol.includes('XAG'))?.last || 31.4;
      document.getElementById('gold-silver-ratio').textContent = (gold / silver).toFixed(2) + 'x';
    }

    // AAPL SVG Candlestick & Secondary RSI Render
    function renderAaplChart() {
      const svg = document.getElementById('aapl-svg');
      const width = 700;
      const mainHeight = 200;
      const subTop = 215;
      const subHeight = 70;
      const subBottom = subTop + subHeight;
      const padLeft = 20;
      const padRight = 50;

      const prices = AAPL_DATA.flatMap(d => [d.low, d.high]);
      const minP = Math.min(...prices) - 2;
      const maxP = Math.max(...prices) + 2;
      const rangeP = maxP - minP;

      const getY = p => mainHeight - 10 - ((p - minP) / rangeP) * (mainHeight - 25);
      const stepX = (width - padLeft - padRight) / AAPL_DATA.length;

      let candleHtml = '';
      let smaPoints = [];
      let emaPoints = [];
      let rsiPoints = [];
      let rsiAreaPoints = [];

      AAPL_DATA.forEach((c, i) => {
        const x = padLeft + i * stepX + stepX / 2;
        const yOpen = getY(c.open);
        const yClose = getY(c.close);
        const yHigh = getY(c.high);
        const yLow = getY(c.low);
        const isBull = c.close >= c.open;
        const color = isBull ? '#10b981' : '#ef4444';

        // Wick
        candleHtml += \`<line x1="\${x}" y1="\${yHigh}" x2="\${x}" y2="\${yLow}" stroke="\${color}" stroke-width="1.2"/>\`;
        // Body
        const top = Math.min(yOpen, yClose);
        const bHeight = Math.max(Math.abs(yClose - yOpen), 2);
        candleHtml += \`<rect x="\${x - 2.5}" y="\${top}" width="5" height="\${bHeight}" fill="\${color}" rx="0.5"/>\`;

        if (c.ma20) smaPoints.push(\`\${x},\${getY(c.ma20)}\`);
        if (c.ema9) emaPoints.push(\`\${x},\${getY(c.ema9)}\`);

        const rsiVal = c.rsi !== undefined ? c.rsi : 50;
        const yRsi = subTop + (1 - rsiVal / 100) * subHeight;
        rsiPoints.push(\`\${x.toFixed(1)},\${yRsi.toFixed(1)}\`);
      });

      if (rsiPoints.length > 0) {
        const firstX = padLeft + stepX / 2;
        const lastX = padLeft + (AAPL_DATA.length - 1) * stepX + stepX / 2;
        rsiAreaPoints = [\`\${firstX},\${subBottom}\`, ...rsiPoints, \`\${lastX},\${subBottom}\`];
      }

      // Horizontal Volume-at-Price Profile (Right Side)
      const numBins = 18;
      const binStep = rangeP / numBins;
      const vapBins = Array.from({ length: numBins }, (_, i) => ({
        priceLow: minP + i * binStep,
        priceHigh: minP + (i + 1) * binStep,
        priceMid: minP + (i + 0.5) * binStep,
        totalVol: 0,
        bullVol: 0,
        bearVol: 0,
      }));

      AAPL_DATA.forEach(c => {
        const cLow = c.low;
        const cHigh = c.high;
        const span = Math.max(0.01, cHigh - cLow);
        const isBull = c.close >= c.open;
        const vol = c.volume || 45000000;
        vapBins.forEach(b => {
          const overlap = Math.max(0, Math.min(b.priceHigh, cHigh) - Math.max(b.priceLow, cLow));
          if (overlap > 0) {
            const fraction = overlap / span;
            const v = vol * fraction;
            b.totalVol += v;
            if (isBull) b.bullVol += v; else b.bearVol += v;
          }
        });
      });

      let maxVapVol = 0;
      let pocBin = vapBins[0];
      vapBins.forEach(b => {
        if (b.totalVol > maxVapVol) {
          maxVapVol = b.totalVol;
          pocBin = b;
        }
      });

      const vapMaxW = 110;
      const profileRightEdge = width - padRight;
      let vapHtml = '';
      vapBins.forEach(b => {
        const barW = maxVapVol > 0 ? (b.totalVol / maxVapVol) * vapMaxW : 0;
        const xStart = profileRightEdge - barW;
        const yTop = getY(b.priceHigh);
        const yBottom = getY(b.priceLow);
        const bHeight = Math.max(2, Math.abs(yBottom - yTop) - 0.8);
        const bullW = b.totalVol > 0 ? (b.bullVol / b.totalVol) * barW : 0;
        const bearW = Math.max(0, barW - bullW);
        const isPoc = b === pocBin;

        vapHtml += \`<rect x="\${xStart}" y="\${yTop}" width="\${bullW}" height="\${bHeight}" fill="#10b981" fill-opacity="\${isPoc ? 0.85 : 0.4}" rx="0.5"/>\`;
        vapHtml += \`<rect x="\${xStart + bullW}" y="\${yTop}" width="\${bearW}" height="\${bHeight}" fill="#ef4444" fill-opacity="\${isPoc ? 0.85 : 0.4}" rx="0.5"/>\`;
        if (isPoc) {
          vapHtml += \`<rect x="\${xStart}" y="\${yTop}" width="\${barW}" height="\${bHeight}" fill="none" stroke="#f59e0b" stroke-width="1.2" rx="0.5"/>\`;
        }
      });

      const yPoc = getY(pocBin.priceMid);
      vapHtml += \`
        <line x1="\${padLeft}" y1="\${yPoc}" x2="\${profileRightEdge}" y2="\${yPoc}" stroke="#f59e0b" stroke-width="1.2" stroke-dasharray="4,3" opacity="0.9"/>
        <rect x="\${profileRightEdge + 2}" y="\${yPoc - 7}" width="46" height="14" rx="2" fill="#f59e0b"/>
        <text x="\${profileRightEdge + 25}" y="\${yPoc + 3.5}" text-anchor="middle" fill="#04070a" font-size="7.5" font-family="monospace" font-weight="bold">POC $\${pocBin.priceMid.toFixed(1)}</text>
      \`;

      const smaPolyline = smaPoints.length ? \`<polyline points="\${smaPoints.join(' ')}" fill="none" stroke="#f59e0b" stroke-width="1.5"/>\` : '';
      const emaPolyline = emaPoints.length ? \`<polyline points="\${emaPoints.join(' ')}" fill="none" stroke="#818cf8" stroke-width="1.5"/>\` : '';

      const maxMainVol = Math.max(...AAPL_DATA.map(d => d.volume || 40000000));
      const maxMainVolH = 46;
      const volSma20Coords: string[] = [];
      AAPL_DATA.forEach((c, i) => {
        if (i >= 19) {
          const slice = AAPL_DATA.slice(i - 19, i + 1);
          const avgVol = c.volMa20 || (slice.reduce((acc, it) => acc + (it.volume || 40000000), 0) / 20);
          const x = padLeft + i * stepX + stepX / 2;
          const vH = maxMainVol > 0 ? (avgVol / maxMainVol) * maxMainVolH : 0;
          const y = mainHeight - 10 - vH;
          volSma20Coords.push(\`\${x.toFixed(1)},\${y.toFixed(1)}\`);
        }
      });
      const lastVolSma = AAPL_DATA[AAPL_DATA.length - 1]?.volMa20 || 48500000;
      let volumeHtml = \`
        <line x1="\${padLeft}" y1="\${mainHeight - 10 - maxMainVolH}" x2="\${width - padRight}" y2="\${mainHeight - 10 - maxMainVolH}" stroke="#1e293b" stroke-width="0.8" stroke-dasharray="2,2" opacity="0.6"/>
        <text x="\${padLeft + 4}" y="\${mainHeight - 10 - maxMainVolH - 3}" fill="#64748b" font-size="7.5" font-family="monospace">VOL HISTOGRAM (PEAK \${(maxMainVol / 1000000).toFixed(1)}M)</text>
        <line x1="\${padLeft + 195}" y1="\${mainHeight - 10 - maxMainVolH - 5}" x2="\${padLeft + 208}" y2="\${mainHeight - 10 - maxMainVolH - 5}" stroke="#fbbf24" stroke-width="1.8"/>
        <text x="\${padLeft + 212}" y="\${mainHeight - 10 - maxMainVolH - 3}" fill="#fbbf24" font-size="7.5" font-family="monospace" font-weight="bold">SMA(20): \${(lastVolSma / 1000000).toFixed(2)}M</text>
      \`;
      AAPL_DATA.forEach((c, i) => {
        const x = padLeft + i * stepX + stepX / 2;
        const vH = maxMainVol > 0 ? ((c.volume || 40000000) / maxMainVol) * maxMainVolH : 0;
        const isBull = c.close >= c.open;
        const barW = Math.max(stepX * 0.72, 3);
        const col = isBull ? '#10b981' : '#ef4444';
        const str = isBull ? '#34d399' : '#fb7185';
        volumeHtml += \`<rect x="\${x - barW / 2}" y="\${mainHeight - 10 - vH}" width="\${barW}" height="\${Math.max(vH, 1)}" fill="\${col}" fill-opacity="0.3" stroke="\${str}" stroke-width="0.5" rx="0.5"/>\`;
      });
      if (volSma20Coords.length > 0) {
        volumeHtml += \`
          <polyline points="\${volSma20Coords.join(' ')}" fill="none" stroke="#f59e0b" stroke-width="3" stroke-opacity="0.25" stroke-linecap="round" stroke-linejoin="round"/>
          <polyline points="\${volSma20Coords.join(' ')}" fill="none" stroke="#fbbf24" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        \`;
      }

      const rsiY70 = subTop + (1 - 0.70) * subHeight;
      const rsiY50 = subTop + (1 - 0.50) * subHeight;
      const rsiY30 = subTop + (1 - 0.30) * subHeight;

      const rsiPolyline = rsiPoints.length ? \`
        <polygon points="\${rsiAreaPoints.join(' ')}" fill="#38bdf8" fill-opacity="0.15"/>
        <polyline points="\${rsiPoints.join(' ')}" fill="none" stroke="#38bdf8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      \` : '';

      const lastRsi = AAPL_DATA[AAPL_DATA.length - 1]?.rsi || 62.4;
      const lastX = padLeft + (AAPL_DATA.length - 1) * stepX + stepX / 2;
      const lastY = subTop + (1 - lastRsi / 100) * subHeight;

      svg.innerHTML = \`
        <line x1="\${padLeft}" y1="15" x2="\${width - padRight}" y2="15" stroke="#1e293b" stroke-dasharray="2,2"/>
        <line x1="\${padLeft}" y1="\${mainHeight/2}" x2="\${width - padRight}" y2="\${mainHeight/2}" stroke="#1e293b" stroke-dasharray="2,2"/>
        <line x1="\${padLeft}" y1="\${mainHeight - 10}" x2="\${width - padRight}" y2="\${mainHeight - 10}" stroke="#1e293b" stroke-dasharray="2,2"/>
        
        <!-- Horizontal Volume-at-Price Profile (Right Side) -->
        <g id="vap-profile">
          <rect x="\${profileRightEdge - vapMaxW - 4}" y="10" width="\${vapMaxW + 4}" height="\${mainHeight - 20}" fill="#03070b" fill-opacity="0.5" rx="2"/>
          <line x1="\${profileRightEdge - vapMaxW - 4}" y1="10" x2="\${profileRightEdge - vapMaxW - 4}" y2="\${mainHeight - 10}" stroke="#1e293b" stroke-dasharray="2,2" stroke-width="0.8"/>
          \${vapHtml}
        </g>

        <!-- Volume Histogram at Bottom of Main Chart Panel -->
        <g id="main-volume-histogram">
          \${volumeHtml}
        </g>

        \${candleHtml}
        \${smaPolyline}
        \${emaPolyline}

        <line x1="\${padLeft}" y1="\${mainHeight}" x2="\${width - padRight}" y2="\${mainHeight}" stroke="#334155" stroke-width="1.2"/>
        <rect x="\${padLeft}" y="\${subTop}" width="\${width - padLeft - padRight}" height="\${subHeight}" fill="#04070a" opacity="0.8"/>
        
        <rect x="\${padLeft}" y="\${subTop}" width="\${width - padLeft - padRight}" height="\${rsiY70 - subTop}" fill="#f43f5e" fill-opacity="0.08"/>
        <rect x="\${padLeft}" y="\${rsiY30}" width="\${width - padLeft - padRight}" height="\${subBottom - rsiY30}" fill="#10b981" fill-opacity="0.08"/>

        <line x1="\${padLeft}" y1="\${rsiY70}" x2="\${width - padRight}" y2="\${rsiY70}" stroke="#f43f5e" stroke-width="0.8" stroke-dasharray="3,3" opacity="0.8"/>
        <line x1="\${padLeft}" y1="\${rsiY50}" x2="\${width - padRight}" y2="\${rsiY50}" stroke="#475569" stroke-width="0.7" stroke-dasharray="2,2" opacity="0.6"/>
        <line x1="\${padLeft}" y1="\${rsiY30}" x2="\${width - padRight}" y2="\${rsiY30}" stroke="#10b981" stroke-width="0.8" stroke-dasharray="3,3" opacity="0.8"/>

        <text x="\${width - padRight + 6}" y="\${rsiY70 + 3}" fill="#f43f5e" font-size="8.5" font-family="monospace" font-weight="bold">70 OB</text>
        <text x="\${width - padRight + 6}" y="\${rsiY50 + 3}" fill="#64748b" font-size="8" font-family="monospace">50</text>
        <text x="\${width - padRight + 6}" y="\${rsiY30 + 3}" fill="#10b981" font-size="8.5" font-family="monospace" font-weight="bold">30 OS</text>
        <text x="\${padLeft + 4}" y="\${subTop + 10}" fill="#38bdf8" font-size="8.5" font-family="monospace" font-weight="bold">RSI(14) SECONDARY OSCILLATOR</text>

        \${rsiPolyline}

        <circle cx="\${lastX}" cy="\${lastY}" r="3" fill="#38bdf8" stroke="#04070a" stroke-width="1.5"/>
        <rect x="\${width - padRight + 4}" y="\${Math.max(subTop, Math.min(subBottom - 13, lastY - 6))}" width="34" height="13" rx="2" fill="#0284c7"/>
        <text x="\${width - padRight + 21}" y="\${Math.max(subTop, Math.min(subBottom - 13, lastY - 6)) + 9.5}" text-anchor="middle" fill="#030708" font-size="8" font-family="monospace" font-weight="bold">\${lastRsi.toFixed(1)}</text>
        <g id="offline-crosshair" pointer-events="none"></g>
      \`;

      const last = AAPL_DATA[AAPL_DATA.length - 1];
      const prev = AAPL_DATA[AAPL_DATA.length - 2] || last;
      const diff = last.close - prev.close;
      const diffPct = (diff / prev.close) * 100;
      const el = document.getElementById('aapl-latest');
      const resetLatest = () => {
        el.textContent = \`$\${last.close.toFixed(2)} (\${diff >= 0 ? '+' : ''}\${diffPct.toFixed(2)}%) | POC $\${pocBin.priceMid.toFixed(1)} | RSI \${lastRsi.toFixed(1)}\`;
        el.className = diff >= 0 ? 'green' : 'red';
        const crosshairG = document.getElementById('offline-crosshair');
        if (crosshairG) crosshairG.innerHTML = '';
      };
      resetLatest();

      svg.addEventListener('mousemove', (e) => {
        const rect = svg.getBoundingClientRect();
        const mouseX = ((e.clientX - rect.left) / rect.width) * width;
        if (mouseX < padLeft || mouseX > width - padRight) {
          resetLatest();
          return;
        }
        const idx = Math.max(0, Math.min(AAPL_DATA.length - 1, Math.floor((mouseX - padLeft) / stepX)));
        const c = AAPL_DATA[idx];
        const crosshairG = document.getElementById('offline-crosshair');
        if (!c || !crosshairG) return;

        const x = padLeft + idx * stepX + stepX / 2;
        const yPrice = getY(c.close);
        const isBull = c.close >= c.open;
        const pColor = isBull ? '#10b981' : '#ef4444';
        const rsiVal = c.rsi || 50;
        const yRsi = subTop + (1 - rsiVal / 100) * subHeight;
        const maxVol = Math.max(...AAPL_DATA.map(d => d.volume || 40000000));
        const maxMainVolH = 46;
        const vHeight = ((c.volume || 40000000) / maxVol) * maxMainVolH;
        const yVolTop = mainHeight - 10 - vHeight;
        const timeBadgeX = Math.max(padLeft, Math.min(width - padRight - 66, x - 33));

        crosshairG.innerHTML = \`
          <!-- Vertical guide line extending fully through main chart and volume sub-panel -->
          <line x1="\${x}" y1="10" x2="\${x}" y2="\${subBottom}" stroke="#38bdf8" stroke-width="2.5" opacity="0.18"/>
          <line x1="\${x}" y1="10" x2="\${x}" y2="\${subBottom}" stroke="#38bdf8" stroke-width="1.2" stroke-dasharray="3,2" opacity="0.9"/>
          <circle cx="\${x}" cy="10" r="2" fill="#38bdf8"/>
          <circle cx="\${x}" cy="\${mainHeight}" r="2" fill="#38bdf8" opacity="0.8"/>

          <!-- Volume Alignment Marker (Main Panel Volume Histogram) -->
          <line x1="\${x - 6}" y1="\${yVolTop}" x2="\${x + 6}" y2="\${yVolTop}" stroke="#ffffff" stroke-width="1.5"/>
          <circle cx="\${x}" cy="\${yVolTop}" r="4.5" fill="\${pColor}" fill-opacity="0.4" stroke="\${pColor}" stroke-width="1.2"/>
          <circle cx="\${x}" cy="\${yVolTop}" r="2" fill="#ffffff" stroke="\${pColor}" stroke-width="1"/>

          <!-- Price Crosshair Line & Target -->
          <line x1="\${padLeft}" y1="\${yPrice}" x2="\${width - padRight}" y2="\${yPrice}" stroke="\${pColor}" stroke-width="1" stroke-dasharray="3,2" opacity="0.85"/>
          <circle cx="\${x}" cy="\${yPrice}" r="5" fill="\${pColor}" fill-opacity="0.3" stroke="\${pColor}" stroke-width="1.2"/>
          <circle cx="\${x}" cy="\${yPrice}" r="2" fill="#ffffff" stroke="\${pColor}" stroke-width="1"/>

          <!-- RSI Crosshair Line & Target -->
          <line x1="\${padLeft}" y1="\${yRsi}" x2="\${width - padRight}" y2="\${yRsi}" stroke="#38bdf8" stroke-width="1" stroke-dasharray="3,2" opacity="0.85"/>
          <circle cx="\${x}" cy="\${yRsi}" r="4" fill="#38bdf8" fill-opacity="0.3" stroke="#38bdf8" stroke-width="1.2"/>

          <!-- Exact Price Badge -->
          <rect x="\${width - padRight + 3}" y="\${yPrice - 7}" width="46" height="14" rx="2" fill="\${pColor}"/>
          <text x="\${width - padRight + 26}" y="\${yPrice + 3.5}" text-anchor="middle" fill="#ffffff" font-size="8" font-family="monospace" font-weight="bold">$\${c.close.toFixed(2)}</text>

          <!-- Exact RSI Badge -->
          <rect x="\${width - padRight + 3}" y="\${yRsi - 7}" width="46" height="14" rx="2" fill="#0284c7"/>
          <text x="\${width - padRight + 26}" y="\${yRsi + 3.5}" text-anchor="middle" fill="#ffffff" font-size="8" font-family="monospace" font-weight="bold">RSI \${rsiVal.toFixed(1)}</text>

          <!-- Exact Timestamp Badge -->
          <rect x="\${timeBadgeX}" y="\${subBottom + 2}" width="66" height="13" rx="2" fill="#0f172a" stroke="#0284c7" stroke-width="1"/>
          <text x="\${timeBadgeX + 33}" y="\${subBottom + 11.5}" text-anchor="middle" fill="#38bdf8" font-size="7.5" font-family="monospace" font-weight="bold">\${c.date}</text>
        \`;

        el.textContent = \`\${c.date} | $\${c.close.toFixed(2)} | VOL \${((c.volume || 0)/1000000).toFixed(1)}M | RSI \${rsiVal.toFixed(1)}\`;
        el.className = isBull ? 'green' : 'red';
      });

      svg.addEventListener('mouseleave', resetLatest);
    }

    // Initialize
    updateClocks();
    renderIndices();
    renderHeatmap();
    renderMetals();
    renderAaplChart();
    setInterval(updateClocks, 1000);
  </script>
</body>
</html>`;
}
